### ISSUE TITLE
Device functionality and library applicability

### ISSUE THREAD

**Issue by dzalf** [RobTillaart/PCA9553#9]
Dear Rob

First of all, thank you for the fantastic job you do for the Arduino and, in general, for the embedded communities.

I have a simple question regarding the PCA9553 functionalities.

The datasheet labels this device as an I2C "LED Blinker" and praises its value as a "resources saver", where the maximum PWM frequency is 44 Hz. 

This value should be enough to maintain good _persistence of vision_ and virtually reproduce any colour with an 8-bit resolution by keeping the RGB channels active. Is this right? In other words, can the 4 channels be driven simultaneously with the maximum PWM frequency value at different duty cycles?

I plan to use this chip with a "dumb" RGBW LED for general debugging indication on a custom ESP32-based board. By using it, I might as well save some pins from my MCU. I typically use 3 PWM-capable pins from my MCU connected to an RGB LED to indicate what "routine sections" are being executed, error messages, and such.

My current setup looks something like this (it is a hierarchical sheet, so don't worry about the I2C pull-ups):

![image](https://github.com/user-attachments/assets/6f9f050e-4bb1-4c87-921a-be5e38c674cc)

Based on this, I guess my second question is if the library could be extended to use it as a replacement for the [RGBLed](https://github.com/wilmouths/RGBLed) from @wilmouths but instead of using direct MCU pins an I2C object would be "abstracted" into the library.

Thanks

Best wishes

**Comment by RobTillaart** [comment]
thanks for your questions, 

Will look into them asap, might take a few days.

**Comment by RobTillaart** [comment]
> This value should be enough to maintain good persistence of vision and virtually reproduce any colour with an 8-bit resolution by keeping the RGB channels active. Is this right? 

44 Hz should give quite acceptable quality, movies used to be 25 frames per second. On the other hand display-refreshes start from 60 to a 240(?) Hz to get crispness. I recall that working at a 60 Hz display (VGA) one could notice the refresh frequencies, so for 44 Hz I expect (some) people might notice but it could be enough.

> In other words, can the 4 channels be driven simultaneously with the maximum PWM frequency value at different duty cycles?

From the readme.md

_The device has two PWM "generators", 0 and 1, and one can set the duty cycle and the frequency by means of a pre-scaler.
Every output channel 0..3 can select to which PWM generator it is connected, or if it is set to ON or OFF._

![image](https://github.com/user-attachments/assets/9cd2e95a-c9d7-4f25-b2ef-3259500934f6)

So according you can only select two different duty cycles as every channel has to select from which PWM generator it gets it signal.  To control an RGBW led with 4 different duty cycles you would need 4 PWM generators, so you could solve this with two PCA9553's.

You can reduce your color space to only do PWM on 2 colors only and the other two are 0 or 1. That would still give you a lot of colors but not a full spectrum. You will need to remap colors but it could be good enough. 

----

> I typically use 3 PWM-capable pins from my MCU connected to an RGB LED to indicate what "routine sections" are being executed, error messages, and such.

Have a look at my heartbeat class - https://github.com/RobTillaart/HeartBeat
Although this uses a single color, it has a similar line of thinking.

**Comment by RobTillaart** [comment]
> Based on this, I guess my second question is if the library could be extended to use it as a replacement for the [RGBLed](https://github.com/wilmouths/RGBLed) from @wilmouths but instead of using direct MCU pins an I2C object would be "abstracted" into the library.

Need to study that library, but given the PCA9553 has only 2 PWM I expect the answer will be no (at least not 100%).

**Comment by RobTillaart** [comment]
Had a quick look at the RGBled library which is quite nice and straightforward.

Some observations in no particular order
- straightforward library with nice functional API
- I like the COMMON_ANODE parameter.
- some code is (minor) blocking (loops, delay), which can be an unwanted effect. An asynchronous version might be interesting.
- code could be simplified by using unsigned int for RGB (no need to constrain for < 0 )
- the RGBlib doesn't support the WHITE channel you need, but that could be updated.
- the RGBlib uses 3 PWM signals so the PCA9553 cannot replace it as it has only 2 PWM signals.
- your setup would need 4 PWM's for full control.

So to answer your second question, the PCA9553 library cannot be extended to the level you need. 
Using two PCA9553's in parallel for one RGBW led would solve it.

Hopes this answers your questions.

**Comment by dzalf** [comment]
Dear Rob

Thank you for your highly detailed answers. This clarifies A LOT. 


> > Based on this, I guess my second question is if the library could be extended to use it as a replacement for the [RGBLed](https://github.com/wilmouths/RGBLed) from @wilmouths but instead of using direct MCU pins an I2C object would be "abstracted" into the library.
> 
> Need to study that library, but given the PCA9553 has only 2 PWM I expect the answer will be no (at least not 100%).

I had not thought about the chip's limitations until you clarified that I would have only 2 PWM generators. Based on this, I am afraid that the coding of my applications will become much more complex only to light up one LED and a handful of colours.

My overall goal is precisely to reduce overheads on my main application by delegating the PWM control to the hardware PWMs due to their "setup and forget" nature. This is the reason why I still refuse to use Neopixels since they consume precious clock cycles,

> Had a quick look at the RGBled library which is quite nice and straightforward.
> 
> Some observations in no particular order
> 
> * straightforward library with nice functional API
> * I like the COMMON_ANODE parameter.
> * some code is (minor) blocking (loops, delay), which can be an unwanted effect. An asynchronous version might be interesting.
> * code could be simplified by using unsigned int for RGB (no need to constrain for < 0 )
> * the RGBlib doesn't support the WHITE channel you need, but that could be updated.
> * the RGBlib uses 3 PWM signals so the PCA9553 cannot replace it as it has only 2 PWM signals.
> * your setup would need 4 PWM's for full control.
> 
> So to answer your second question, the PCA9553 library cannot be extended to the level you need. Using two PCA9553's in parallel for one RGBW led would solve it.
> 
> Hopes this answers your questions.

Indeed, this library has been my _de facto_ library to drive RGB LEDs for general debugging and signalling. However, as you pointed it out, its main flaw is perhaps its intrinsic blocking nature. For my intents and purposes, it is enough.

Based on your answers, I think I will have to use other alternatives, like the PCA9685 despite I will have to "sacrifice" the spare 12 channels. 

I appreciate your help. I will be closing this.

Cheers

Dan

**Comment by RobTillaart** [comment]
@dzalf 

If you have a spare Atmel328 you can create your own 6 channel PWM device. 
Make the Arduino a SPI / I2C / Serial slave and use one of the 6 PWM pins (3,5,6,9,10,11)

A quick example for Serial.

```cpp
//    FILE: Serial2PWM.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
//    DATE: 2024-11-25
// PURPOSE: demo
//     URL: https://github.com/RobTillaart/PCA9553/issues/9

//
//  command looks like "port value\n";
//   port  = 0..5
//   value = 0..255;
//

#include "Arduino.h"

char buffer[24];
int idx = 0;
int PWMpins[6] = {3, 5, 6, 9, 10, 11};

void setup()
{
  Serial.begin(115200);
  while (!Serial);
  Serial.println(__FILE__);

  // empty command buffer;
  idx = 0;
  buffer[0] = 0;
}

void loop()
{
  if (Serial.available())
  {
    char c = Serial.read();
    buffer[idx++] = c;
    buffer[idx] = 0;
    if ((c == 13) || (c == 10))  //  command delimiter
    {
      int port, value;
      int n = sscanf(buffer, "%d %d", &port, &value);
      if ((n == 2) && (port < 6))
      {
        analogWrite(PWMpins[port], value);
        Serial.println("S");  //  success
      }
      else
      {
        Serial.println("F");  //  fail
      }
      idx = 0;
      buffer[0] = 0;
    }
    //  too much data?
    if (idx > 20)
    {
      idx = 0;
      buffer[0] = 0;
    }
  }
}

//  -- END OF FILE --
```

**Comment by RobTillaart** [comment]
Not tested, an I2C PWM slave,

```cpp
//
//    FILE: I2C_PWM_slave.ino
//  AUTHOR: Rob Tillaart
// VERSION: 0.1.0
//    DATE: 2024-11-25
// PURPOSE: demo
//     URL: https://github.com/RobTillaart/PCA9553/issues/9
//

#include <Wire.h>

#define I2CADDRESS    0x30

int PWMpins[6] = {3, 5, 6, 9, 10, 11};

void setup()
{
  Serial.begin(115200);
  Serial.println(__FILE__);  //  for debugging

  //  hard coded address
  Wire.begin(I2CADDRESS);
  //  adjust if needed
  Wire.setClock(100000);

  Wire.onRequest(requestEvent);
  Wire.onReceive(receiveEvent);
}

void loop()
{
}

void receiveEvent(int count)
{
  int port = Wire.read();
  int value = Wire.read();

  Serial.print(count);
  if (port < 6)
  {
    analogWrite(PWMpins[port], value);
    Serial.println("S");  //  success
  }
  else
  {
    Serial.println("F");  //  fail
  }
}

//  optional.
void requestEvent()
{
  Wire.write(0);
}

//  -- END OF FILE --
```

**Comment by dzalf** [comment]
@RobTillaart 

This is pure _programmatic_ gold. Thank you for this.

In fact, at some point I thought of implementing something like this on an ATiny85 or similar, however, I wanted to have an all-in-one solution.

I feel like your solution is worth testing, though!

While browsing Mouser and NXP's websites, I found the [PCA9632](https://www.nxp.com/docs/en/data-sheet/PCA9632.pdf), and in a _lucky strike_ (pun intended), some lucky guy named @SomeLucky1 created a [library](https://github.com/SomeLucky1/PCA9632) for it, and it is precisely targetted at RGBW LEDs! His library happens to be a fork from another repo aimed at the [PCA9633](https://www.nxp.com/docs/en/data-sheet/PCA9633.pdf)

Apparently, both devices are nearly identical apart from higher efficiency and faster I2C bus speed on the PCA9632.

**Comment by RobTillaart** [comment]
The advantage of using an UNO as "co-processor" is that you can expand its behavior to what you need (and beyond).
- single byte command to switch off all PWM lines
- use a free line for a buzzer?
- short commands for often used sequences.
- short commands for complex sequences (eg siren, transitions) w- store them in EEPROM or in PROGMEM
- additional commands could do IO
- buffer the analog values in an array and retrieve them from the device
- ...

I'll have a look at those libraries.

**Comment by RobTillaart** [comment]
Interesting libraries and I think they look exactly to what you need.
If you make a commercial application you need to check the license.

**Comment by RobTillaart** [comment]
@dzalf 
I have added the PCA9632/33 on my backlog to make an MIT licensed library (less restrictive)

BTW, have you considered my PCA9634 library which is an 8 channel LED driver, allows you to control 2 RGBW leds.

**Comment by RobTillaart** [comment]
Created a repository as placeholder, will make a minimalistic version that allows setting each channel.
- https://github.com/RobTillaart/PCA9632

**Comment by RobTillaart** [comment]
@dzalf 

Created a develop branch and PR for an initial version of the PCA9632 library. 
Could copy / paste / modify  a lot from the PCA9634.
Not tested with hardware, however it compiles on Arduino UNO and ESP32.

Not functionally complete, however for now spent enough time on it.
If you have remarks please open an issue in the PCA9632 repository.

**Comment by dzalf** [comment]
Hey, @RobTillaart 

Your help is very much appreciated. 

This is awesome.

Thanks for taking the time to develop this. I will definitely be testing it and I will get back to you if I run into any issues. 

I need to finish my hardware design first to be able to test it.

Best wishes

Dan

**Comment by dzalf** [comment]
> @dzalf I have added the PCA9632/33 on my backlog to make an MIT licensed library (less restrictive)
> 
> BTW, have you considered my PCA9634 library which is an 8 channel LED driver, allows you to control 2 RGBW leds.

Well. I have not checked that chip's datasheet but I will. My application only requires one LED so I think the PCA9632 will suffice

**Comment by RobTillaart** [comment]
FYI, version 0.1.0 released.

**Comment by dzalf** [comment]
> FYI, version 0.1.0 released.

Wow, @RobTillaart. Just Wow!

Thanks again

🍻

**Comment by RobTillaart** [comment]
@dzalf 
FYI
Created a separate repo for the I2C PWM generator sketch - https://github.com/RobTillaart/I2C_PWM_generator
Will merge it tomorrow after a fresh review.
